<?php

namespace AppBundle\Repository;

/**
 * car_serviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class car_serviceRepository extends \Doctrine\ORM\EntityRepository
{
}
